### ISSUE TITLE
extraction gives out empty dae file

### ISSUE THREAD

**Issue by darthron1975** [connorh315/Hologram#2]
When i try opening the dae fíle in blender the meshes show up in the content browser but but the viewport is empty and this isn't a scaling issue in blender as i tried change the scale and it didn't work

**Comment by connorh315** [comment]
What map did you try to export?

**Comment by darthron1975** [comment]
1WIZARDOFOZA

**Comment by connorh315** [comment]
Are you able to share the DAE file that was created? Also did you use the GSC from the PATCH dat or from the original GAME dat?

**Comment by darthron1975** [comment]
here is the link:"https://drive.google.com/file/d/1M7Dy4TmOyFnVNPwDDN76log1yGDmi1Wg/view?usp=sharing" and i don't know as i always extract all the dat files of a game at once

**Comment by connorh315** [comment]
Are you from a country that uses commas instead of periods to represent decimals? I knew of this issue but didn't have anyone to test it for me. I'll make some changes to Hologram in hopes that I can fix it.

**Comment by darthron1975** [comment]
I'm from Germany and am using the German version of windows 10

**Comment by connorh315** [comment]
That makes sense. I've just released version [1.0.1](https://github.com/connorh315/Hologram/releases/tag/H1.0.1) - Would you be able to let me know if that fixes the issue?

**Comment by darthron1975** [comment]
that fixed it thanks
